apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: chat-frontend
      version: v1
  template:
    metadata:
      labels:
        app: chat-frontend
        version: v1
    spec:
      containers:
        - name: container-1
          image: chatgpt-next-web:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: BASE_URL
              value: http://rwkv-runner-svc
          resources:
            requests:
              cpu: 2000m
              memory: 4096Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-svc
  labels:
    app: chat-frontend
    version: v1
  namespace: default
  annotations: {}
spec:
  selector:
    app: chat-frontend
    version: v1
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 3000
      nodePort: 0
      port: 80
      protocol: TCP
  type: NodePort
  isSupportProtocolVersion: true
