apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwkv-runner
  namespace: default
spec:
  selector:
    matchLabels:
      app: rwkv-runner
      version: v1
  template:
    metadata:
      labels:
        app: rwkv-runner
        version: v1
    spec:
      containers:
        - name: container-1
          image: rwkv-runner:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 2000m
              memory: 4096Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: rwkv-runner-svc
  labels:
    app: rwkv-runner
    version: v1
  namespace: default
  annotations: {}
spec:
  selector:
    app: rwkv-runner
    version: v1
  ports:
    - name: cce-service-0
      targetPort: 8000
      nodePort: 0
      port: 80
      protocol: TCP
  type: ClusterIP
  isSupportProtocolVersion: true
